version: "3.9"

services:
  redis:
    image: "redis:alpine3.13"
    ports:
      - "6379:6379"
    networks:
      sim1_nw:

networks:
  sim1_nw:
    ipam:
      driver: default
      config:
        - subnet: 172.28.3.0/24
